version: '3.7'
services:
  postgres-b:
    image: postgres:10
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres-b:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  postgres-b1:
    image: postgres:10
    ports:
      - 5433:5432
    volumes:
      - ./data/postgres-b1:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  postgres-b2:
    image: postgres:10
    ports:
      - 5434:5432
    volumes:
      - ./data/postgres-b2:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres